# 동기 (sync) 프로그래밍
- 코드가 순서대로 실행된다. 위에서 아래로
- 작업이 완료될 때까지 중단할 수 없다.
- 순서대로 되니까 이전 작업이 끝날때까지 기다려야 다음 작업이 실행된다.

# 비동기 (async) 프로그래밍
- 임의의 순서 또는 동시에 작업 실행 가능
- 현재 코드의 실행 결과를 받지 않고 이후 코드를 수행하는 기법
- 방법에는 callback, Future, async-await 방식이 있다.

## callback : 실행 가능한 함수를 인자로 전달하여 특정 상황이 발생할 때 호출되게 하는 방식
- 함수의 실행순서가 보장된다. 그렇지만?
- 지옥이 펼쳐질 수도 있다.
  ```
  step1(function (value1) {
    step2(function (value2) {
        step3(function (value3) {
            step4(function (value4) {
                step5(function (value5) {
                    step6(function (value6) {
                        step7(function (value7) {
                            step8(function (value8) {
                                step9(function (value9) {
                                  step10(function (value10) {
                                  // Do something with value10
                                  });
                               });
                            });
                         });
                     });
                  });
              });
          });
      });
  });
  ```

## Future : 미래에 완료되는 객체, 미래에 받아올 값을 의미한다.
- 많은 API는 Future 타입을 리턴
- Future 함수는 함수 본문 앞에 async 키워드를 지정하고 대기하고 싶은 비동기 함수를 싱행할 때 await 키워드를 사용하면 순서대로 실행된다.
### then()
- 결과를 then() 함수를 통해 받을 수 있다.
- then() 함수로 전달되는 콜백 함수에 다음에 실행할 코드를 작성하면 된다. -> 다음 코드도 Future 라면 체인으로 then() 을 이어나갈 수 있다.
- 불필요한 인자라면 _를 쓴다.(써야한다 x, 보통 쓴다 o)
  ```
  final user = {
    'email': 'abc@abc.com',
    'password': '123456',
    'name': 'John Doe',
  }

  saveDb(user)
      .then((_) => sendEmail(user))
      .then((_) => getResult(user))
      .then((value) => print(value));
  ```
- catchError() 함수를 사용해 에러처리를 할 수 있다. -> 에러를 발생시킬 때는 Future.error() 를 사용한다.
- throw Exception() 으로 예외를 발생시킬 수 있다.
- 성공시 (then)을, 에러시 (catchError)로 핸들링한다.
- whenComplete() 는 성공/실패에 관계없이 실행한다.
  ### then() 의 문제점
  - 동기식 코드보다 결과 예측이 어렵다.
  - 단계가 많아지면 체이닝 방식이 쉽지않다.
  - 로직이 복잡해지면 적절한 예외처리에 용이하지 않다.
### async-await
- 깔끔한 코드를 제공
- await 키워드는 해당 Future 가 끝날때까지 실행을 기다린다.
- async 키워드가 있는 함수에서만 await 함수를 사용할 수 있다.
